# Site settings
title: Learnings and Thoughts
email: wenfengzhuo@gmail.com
description: Learning and Thoughts
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
host: 172.31.38.1
port: 80
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: wenfengzhuo
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/wenfengzhuo/blog/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/wenfengzhuo/blog/new/master

disqus_shortname: wenfengzhuo
disqus_url: "http://zhuowenfeng.com"

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false

# Experimental
incremental: true
